print("What's the name of the gift giver?")
name = input()
print("What's the present they gave you?")
present = input()
print("How old were you on your birthday?")
age = int(input())
print("What's your name?")
yourName = input()
print("Dear " + name + ", ")
print("")
print("Thank you for the " + present + ". ")
print("I really like it. I can't believe ")
print("I am already " + str(age) + " years old, but ")
print("it doesn\'t feel much differen than being ")
print(str(age-1) + ".")
print("")
print("Sincerely, ")
print("")
print(yourName)
print("")
print("")
